releaseTargetBranch: master
commentOnReleasablePR: true
labelsToIgnore: ["pr-release: don't release"]
releaseName: "PR Release Bot Release {version}"
releaseLabel: "pr-release: release"
noReleaseLabel: "pr-release: won't release"